version: '3.7'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    ports:
      - 5432:5432
    image: postgres:12.0-alpine
    volumes:
      - shelter_postgres_data_dev:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev.db

volumes:
  shelter_postgres_data_dev:
    external: true
