# Generated by Django 4.1.2 on 2023-08-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalmodel',
            name='age',
            field=models.DateField(),
        ),
    ]
