# Generated by Django 4.1.2 on 2023-08-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_animalmodel_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalmodel',
            name='category',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='MALE', max_length=20),
            preserve_default=False,
        ),
    ]
