# Generated by Django 4.1.2 on 2023-08-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_category_animalmodel_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalmodel',
            name='vaccinated',
            field=models.BooleanField(),
        ),
    ]
